---
- name: Set up OpenvSwitch
  hosts: localhost
  tasks:
    - name: Install OpenvSwitch
      import_role:
        name: openvswitch
        tasks_from: install.yml

- name: Set up OpenvSwitch ports
  hosts: localhost
  tasks:
    - import_role:
        name: openvswitch
        tasks_from: setup.yml

- name: Provision CoreDNS pod
  hosts: localhost
  tasks:
    - name: Create CoreDNS pod
      import_role:
        name: external_dns
        tasks_from: pods.yml
