---
- name: Install OpenvSwitch
  package:
    name: openvswitch-switch
    state: present

- name: Enable OVS services
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    state: started
  with_items:
    - openvswitch-switch
    - ovsdb-server
    - ovs-vswitchd
