---
- name: Create bridges
  template:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.name }}
    src: ifcfg-{{ item.name }}.j2
    owner: root
    group: root
    mode: 644
  when: "{{ lookup('env', item.manage_env) }}" == "y"
  with_items:
    - { name: "baremetal", manage_env: "MANAGE_INT_BRIDGE" }
    - { name: "provisioning", manage_env: "MANAGE_PRO_BRIDGE" }

# - name: NAT the interface
#   iptables:
#     action: append
#     chain: POSTROUTING
#     table: nat
#     out_interface: metal3
#     jump: MASQUERADE

